### PR TITLE
Add bolt support

### PR DESCRIPTION
**Pull request by kwelch**
Adds an example bolt directory and updates the script to pull bolt projects.

### CODE REVIEW

**Comment by azz** [comment]
Awesome. Want to update documentation to mention bolt support?

**Comment by kwelch** [comment]
Absolutely! I am also confirming that this worked properly. I believe it should have captured a third package, if so I will update this further to ensure it captures that as well.

**Comment by kwelch** [comment]
This should be all set. Let me know if there is anything else.

**Review by azz — APPROVED** [review]

**Comment by azz** [comment]
Thanks!

**Pull request merged**
